// Where things stand, generated. Run with `npm run state`.
//
// A hand-written status file is worse than none: it goes stale in one commit
// and then it lies, which is exactly the failure the review console's
// "Claims that do not match the code" section exists to catch. So this reads
// git and the review queue and writes what it finds.
//
// It reports *facts* — what is dirty, what landed, what is queued. The *why*
// behind anything in flight belongs in review/review-notes.json, per the
// notepad rule in CLAUDE.md. A dirty file with no note explaining it is the
// signal that a session stopped mid-thought.

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const sh = (cmd) => execSync(cmd, { encoding: 'utf8' }).trim();

/** Which part of the product a path belongs to, in the words CLAUDE.md uses. */
function area(file) {
  if (file.startsWith('src/domain/')) return 'src/domain — the shared truth';
  if (file.startsWith('src/review/')) return 'src/review — the console';
  if (file.startsWith('src/styles/')) return 'src/styles';
  if (file.startsWith('src/state/')) return 'src/state';
  const layout = file.match(/^src\/components\/([a-z0-9]+)\//i);
  if (layout) return `src/components/${layout[1]} — one layout`;
  if (file.startsWith('src/components/')) return 'src/components — shared, reaches most layouts';
  if (file.startsWith('review/')) return 'review — the notes';
  if (file.startsWith('docs/') || file.endsWith('.md')) return 'docs';
  if (file.startsWith('scripts/')) return 'scripts';
  return 'other';
}

const branch = sh('git rev-parse --abbrev-ref HEAD');
const status = sh('git status --porcelain') || '';

const changed = status
  .split('\n')
  .filter(Boolean)
  .map((line) => ({ code: line.slice(0, 2).trim(), file: line.slice(3).replace(/^"|"$/g, '') }));

const grouped = new Map();
for (const entry of changed) {
  const key = area(entry.file);
  if (!grouped.has(key)) grouped.set(key, []);
  grouped.get(key).push(entry);
}

// The review queue, read the same way the report reads it: a note is only
// waiting on us if the last word in its thread is not already ours.
let queue = { total: 0, waiting: [] };
try {
  const notes = JSON.parse(readFileSync('review/review-notes.json', 'utf8'));
  const values = Object.values(notes);
  queue.total = values.length;
  queue.waiting = values.filter((note) => {
    if (!['open', 'commented', 'second'].includes(note.status)) return false;
    const last = (note.thread ?? []).at(-1);
    return last?.from !== 'claude';
  });
} catch {
  queue = null;
}

const line = (s) => s + '\n';
let out = '';
out += line('# Where things stand');
out += line('');
out += line('Generated by `npm run state` — do not edit by hand. It reports facts;');
out += line('the reasoning behind anything in flight belongs in the review notes.');
out += line('');
out += line(`**Branch:** \`${branch}\` · **Generated:** ${new Date().toISOString().slice(0, 16).replace('T', ' ')}Z`);
out += line('');

out += line('## Uncommitted work');
out += line('');
if (!changed.length) {
  out += line('Working tree is clean.');
} else {
  out += line(`${changed.length} file${changed.length === 1 ? '' : 's'} changed, by area:`);
  out += line('');
  const order = [...grouped.entries()].sort((a, b) => b[1].length - a[1].length);
  for (const [key, entries] of order) {
    out += line(`**${key}** — ${entries.length}`);
    out += line('');
    for (const e of entries) out += line(`- \`${e.file}\`${e.code === '??' ? ' *(new)*' : ''}`);
    out += line('');
  }
  out += line('A dirty file with no review note explaining it means a session stopped');
  out += line('mid-thought. Read the diff before building on it.');
}
out += line('');

out += line('## Last landed');
out += line('');
for (const c of sh('git log --oneline -6').split('\n')) out += line(`- ${c}`);
out += line('');

out += line('## Review queue');
out += line('');
if (!queue) {
  out += line('Could not read `review/review-notes.json`.');
} else if (!queue.waiting.length) {
  out += line(`${queue.total} notes. **Nothing is waiting on a code pass.**`);
} else {
  out += line(`${queue.total} notes · **${queue.waiting.length} waiting on a code pass:**`);
  out += line('');
  for (const n of queue.waiting) {
    const text = (n.comment || n.reason || '').replace(/\s+/g, ' ').slice(0, 90);
    const where = n.anchor?.source ?? n.anchor?.layout ?? '';
    out += line(`- **${n.label ?? n.id}**${where ? ` — \`${where}\`` : ''}${text ? `  \n  ${text}${text.length >= 90 ? '…' : ''}` : ''}`);
  }
  out += line('');
  out += line('Full text and threads: `review/REVIEW-NOTES.md` (top ~50 lines).');
}
out += line('');

mkdirSync('docs', { recursive: true });
writeFileSync('docs/STATE.md', out);
console.log(`docs/STATE.md written — ${changed.length} changed, ${queue ? queue.waiting.length : '?'} waiting`);
