/**
 * The run, written down for whoever reads it next — which is usually a model
 * with none of this conversation.
 *
 * Two documents, because they are two different reads:
 *
 *   STATES.md   every screen the crawl reached, the presses that reach it,
 *               and the file to look at. An index to the pictures.
 *   MOTION.md   every transition, animation and transform — what the CSS
 *               declares, and what pressing things actually did. This is the
 *               one the console's copy button hands over: it is the half of
 *               a design a screenshot cannot show.
 *
 * Both open by saying what they are and how they were made, because a
 * document that arrives in a context window with no framing gets read as
 * ground truth, and this is a recording with known limits.
 */

const bullet = (text) => `- ${text}`;

function frontMatter(report, kind) {
  return [
    `<!-- generated by npm run capture — do not hand-edit -->`,
    `# ${kind}`,
    '',
    `> Captured **${report.at.slice(0, 16).replace('T', ' ')}** at **${report.device.w}×${report.device.h}**`,
    `> (${report.device.dpr}× density) in headless Chrome, driven by the review console.`,
    `> Layouts: ${report.layouts.map((layout) => `\`${layout.id}\``).join(', ')}.`,
    ''
  ].join('\n');
}

/* ------------------------------------------------------------------ */

export function statesMarkdown(report) {
  const out = [frontMatter(report, 'Screens')];

  out.push(
    'Every state below was reached by loading the app fresh and replaying the',
    'presses named under it. That is what makes each one an address rather than',
    'a screenshot: the same list of presses gets you back to the same picture.',
    '',
    'Two images per state, and they answer different questions:',
    '',
    '| | |',
    '|---|---|',
    '| `…-fold.png` | the device viewport exactly as it is — what a phone shows first. |',
    '| `…-full.png` | the whole layout in one image, with the app shell opened up. Its viewport is taller than any phone, so anything keyed on `100dvh` is drawn against a height no device has. Read the layout here; judge the fold in the other one. |',
    ''
  );

  for (const layout of report.layouts) {
    out.push(`## ${layout.id} — ${layout.states.length} states`, '');
    for (const state of layout.states) {
      out.push(`### ${state.name}`);
      out.push('');
      if (state.presses.length) {
        out.push(bullet(`**Press** ${state.presses.map((label) => `“${label}”`).join(' → ')}`));
      } else {
        out.push(bullet('**Press** nothing — this is the app as it opens.'));
      }
      if (state.control) out.push(bullet(`Control: \`${state.control}\``));
      const files = [state.files.fold && `\`${layout.id}/${state.files.fold}\``,
        state.files.full && `\`${layout.id}/${state.files.full}\` (${state.files.fullHeight}px tall)`]
        .filter(Boolean);
      out.push(bullet(`Images: ${files.join(' · ')}`));
      out.push('');
    }
  }

  return `${out.join('\n')}\n`;
}

/* ------------------------------------------------------------------ */

export function motionMarkdown(report) {
  const out = [frontMatter(report, 'Motion')];

  out.push(
    'Paste this into a chat with an AI that is about to work on the interface.',
    '',
    '**What this is.** Every transition, animation and transform in the app, from',
    'two directions: what the stylesheets declare, and what actually moved when',
    'the crawl pressed things. Screenshots cannot carry motion, so without this a',
    'model reading a capture run sees nine still images and infers a static app.',
    '',
    '**What it is not.** It is a recording of one run at one width with one',
    "record's worth of data, one press deep from the front door and two presses",
    'into whatever that revealed. Anything reached by typing, dragging, waiting',
    'or scrolling is absent. Absence here is not evidence.',
    '',
    '**The house rule it is measured against.** `metrics.css` offers three',
    'durations — `--t-motion-short: 150ms`, `--t-motion-medium: 250ms`,',
    '`--t-motion-long: 400ms` — on one easing, `--t-ease`, and says `short` is the',
    'only one a control may use. A duration written as a literal is a fourth',
    'duration nobody agreed to, and is flagged **off-token** below.',
    ''
  );

  /* ---- observed ---- */
  out.push('## What pressing things actually did', '');
  let anyObserved = false;
  for (const layout of report.layouts) {
    const acted = layout.states.filter((state) => (
      state.changed?.moved?.length || state.changed?.appeared?.length
      || state.changed?.swap || state.inFlight?.length
    ));
    if (!acted.length) continue;
    anyObserved = true;
    out.push(`### ${layout.id}`, '');

    for (const state of acted) {
      out.push(`**${state.presses.join(' → ') || state.name}** — \`${state.control ?? 'front door'}\``);
      out.push('');

      for (const animation of state.inFlight ?? []) {
        out.push(bullet(
          `**in flight** — ${animation.kind} \`${animation.name}\` on \`${animation.on}\``
          + `${animation.duration ? `, ${animation.duration}ms` : ''}`
          + `${animation.easing ? ` \`${animation.easing}\`` : ''}`
        ));
      }

      if (state.changed?.swap) {
        out.push(bullet(
          'Replaced the screen — this is a navigation, not an animation.'
          + ` ${state.changed.left} elements left, and what is listed below is only what survived.`
        ));
      }

      for (const change of state.changed?.moved ?? []) {
        out.push(bullet(
          `\`${change.name}\` — ${change.what.join('; ')}`
          + `${change.transition ? ` *(${change.transition})*` : ''}`
        ));
      }

      for (const arrival of state.changed?.appeared ?? []) {
        out.push(bullet(`revealed ${arrival.n > 1 ? `${arrival.n}× ` : ''}\`${arrival.cls}\``));
      }

      if (!state.inFlight?.length && !state.changed?.moved?.length) {
        out.push(bullet('*Nothing was mid-flight when this was sampled — the change was instant, or it had finished.*'));
      }
      out.push('');
    }
  }
  if (!anyObserved) {
    out.push('Nothing moved. Either the crawl was off, or every press in this run',
      'swapped state without animating it.', '');
  }

  /* ---- declared ---- */
  out.push('## What the stylesheets declare', '');
  const offToken = [];
  for (const sheet of report.motionCss?.sheets ?? []) {
    const name = String(sheet.file).split('/').pop();
    out.push(`### ${name}`, '');
    if (sheet.keyframes?.length) {
      out.push(bullet(`**Keyframes:** ${sheet.keyframes.map((frame) => `\`${frame.name}\` (${frame.steps.join(', ')})`).join(' · ')}`));
    }
    for (const move of sheet.moves ?? []) {
      const bits = [
        move.transition && `transition: \`${move.transition}\``,
        move.animation && `animation: \`${move.animation}\``,
        move.transform && `transform: \`${move.transform}\``
      ].filter(Boolean);
      const flag = move.offToken ? ` — **off-token ${move.offToken.map((ms) => `${ms}ms`).join(', ')}**` : '';
      if (move.offToken) offToken.push(`${name} · \`${move.selector}\` — ${move.offToken.join('ms, ')}ms`);
      out.push(bullet(`\`${move.selector}\`${move.within ? ` *${move.within}*` : ''} — ${bits.join('; ')}${flag}`));
    }
    out.push('');
  }

  const shut = report.motionCss?.unreadable ?? [];
  if (shut.length) {
    out.push(
      `${shut.length} stylesheet${shut.length === 1 ? ' was' : 's were'} cross-origin and could not be read`,
      `(${shut.map((file) => String(file).split('/').pop()?.split('?')[0]).join(', ')}).`,
      ''
    );
  }

  if (offToken.length) {
    out.push(
      '## Durations that are not tokens',
      '',
      `${offToken.length} declaration${offToken.length === 1 ? '' : 's'} spell a duration`,
      'rather than naming one. Each is a decision `metrics.css` had already taken.',
      ''
    );
    for (const line of offToken) out.push(bullet(line));
    out.push('');
  }

  return `${out.join('\n')}\n`;
}
